---
## 1. NumPy'a Giriş ve Diziler

### NumPy Nedir ve Neden Önemlidir?

**NumPy**, adından da anlaşılacağı gibi ("Numerical Python"), Python'da **sayısal hesaplamalar** yapmak için kullanılan temel bir kütüphanedir. Özellikle **dizilerle (arrays)** çalışmak için tasarlanmıştır.

Peki, Python'da zaten **listeler** varken neden NumPy'a ihtiyaç duyalım? 🤔

* **Hız:** NumPy dizileri, Python listelerine göre **50 kata kadar daha hızlı** olabilir! Bunun sebebi, NumPy dizilerinin bellekte **tek bir bitişik alanda** saklanmasıdır. Bu sayede bilgisayar verilere çok daha hızlı erişebilir ve işlem yapabilir.
* **Verimlilik:** NumPy, C ve C++ gibi hızlı dillerle yazılmış birçok optimize edilmiş fonksiyona sahiptir ve modern işlemcilerle uyumlu çalışır.
* **Kolaylık:** `ndarray` adı verilen NumPy dizi nesnesi, matematiksel ve mantıksal işlemler için çok sayıda kullanışlı fonksiyon sunar.

**Analoji Zamanı:** Python listelerini, her bir eşyanın evin farklı bir odasında olduğu bir alışveriş listesi gibi düşünebilirsin. Hepsini toplamak zaman alır. NumPy dizisi ise, tüm kitapların yan yana durduğu bir kitaplık gibidir; aradığını bulmak ve almak çok daha hızlıdır! 📚💨

**Eğlenceli Bilgi:** NumPy, Python'daki Pandas, SciPy, Matplotlib gibi neredeyse tüm veri bilimi ve makine öğrenimi kütüphanelerinin temelini oluşturur. Yani NumPy öğrenerek, aslında tüm bu alanların kapısını aralamış oluyorsun!

### NumPy Dizisi (`ndarray`) Oluşturma

NumPy'da diziler oluşturmak için genellikle `numpy` kütüphanesini `np` takma adıyla içe aktarırız:

```python
import numpy as np
```

Sonra `np.array()` fonksiyonu ile listelerden veya demetlerden diziler oluşturabiliriz:

```python
# 0-Boyutlu Dizi (Skaler)
dizi_0b = np.array(42)
print("0B Dizi:", dizi_0b)
print("Boyut:", dizi_0b.ndim) # ndim, dizinin boyut sayısını verir [cite: 15]

# 1-Boyutlu Dizi (Vektör)
dizi_1b = np.array([1, 2, 3, 4, 5])
print("1B Dizi:", dizi_1b)
print("Boyut:", dizi_1b.ndim)

# 2-Boyutlu Dizi (Matris)
dizi_2b = np.array([[1, 2, 3], [4, 5, 6]])
print("2B Dizi:\n", dizi_2b)
print("Boyut:", dizi_2b.ndim)

# 3-Boyutlu Dizi (Tensör)
dizi_3b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3B Dizi:\n", dizi_3b)
print("Boyut:", dizi_3b.ndim)
```

Gördüğün gibi `np.array()` ile farklı boyutlarda diziler yaratabiliyor ve `ndim` özniteliği ile kaç boyutlu olduklarını kolayca öğrenebiliyoruz.

---


In [1]:
import numpy as np

arr_0 = np.array(42)
print(f"Dizi içeriği: {arr_0}")
print(f"Boyut: {arr_0.ndim}")

arr_1 = np.array([1,2,3,4,5])
print(f"Dizi içeriği: {arr_1}")
print(f"Boyut: {arr_1.ndim}")

arr_2 = np.array([[1,2,3],[4,5,6]]) # Matris
print(f"Dizi içeriği {arr_2}")
print(f"Boyut: {arr_2.ndim}")

arr_3 = np.array([[[1,2], [3,4]],[[5,6], [7,8]]]) # Tensör
print(f"Dizi içeriği:\n {arr_3}")
print(f"Boyut: {arr_3.ndim}")

Dizi içeriği: 42
Boyut: 0
Dizi içeriği: [1 2 3 4 5]
Boyut: 1
Dizi içeriği [[1 2 3]
 [4 5 6]]
Boyut: 2
Dizi içeriği:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Boyut: 3


In [2]:
# İndeksleme
# 2 Boyutlu Diziler
arr_2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(f"2B dizi: {arr_2}")

# 1. satır, 4. eleman
print(f"arr_2[0,3]:", arr_2[0,3])

# 2. satır 3. eleman
print(f"arr_2[1,2]:", arr_2[1,2])

# Negatif indeksleme
# 2. satır, sondan 3. eleman
print(f"arr_2[1,-5]:", arr_2[1,-5])

# 3 Boyutlu Diziler
arr_3b = np.array([[[1,2,3],[4,5,6]],[[7,8,11],[9,10,12]]])
print(f"3B dizi: {arr_3b}")
print(f"arr_3b[1,0,2]:", arr_3b[1,0,2])

2B dizi: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr_2[0,3]: 4
arr_2[1,2]: 8
arr_2[1,-5]: 6
3B dizi: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8 11]
  [ 9 10 12]]]
arr_3b[1,0,2]: 11


---

## 2. Dizi Erişimi ve Temel İşlemler: Dilimleme (Slicing)

Şimdi tek tek eleman almak yerine, dizimizin belirli bir **parçasını**, yani bir **dilimini** nasıl alacağımıza bakalım. Buna **dilimleme (slicing)** diyoruz[cite: 18].

Dilimleme için `[başlangıç:bitiş:adım]` sözdizimini kullanırız[cite: 18].

* **`başlangıç`:** Dilimin başlayacağı indeks (dahil).
* **`bitiş`:** Dilimin biteceği indeks (**dahil değil!**).
* **`adım`:** Kaçar kaçar atlayacağımız (varsayılan 1'dir).

### 1-Boyutlu Dizilerde Dilimleme

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# İndeks 1'den 5'e kadar (5 hariç) alalım
print("arr[1:5] =", arr[1:5]) # Çıktı: [2 3 4 5] [cite: 18]

# İndeks 4'ten sona kadar alalım
print("arr[4:] =", arr[4:]) # Çıktı: [5 6 7] [cite: 18]

# Baştan indeks 4'e kadar (4 hariç) alalım
print("arr[:4] =", arr[:4]) # Çıktı: [1 2 3 4] [cite: 18]

# Sondan 3. elemandan sondan 1. elemana kadar (sondaki hariç)
print("arr[-3:-1] =", arr[-3:-1]) # Çıktı: [5 6] [cite: 18]

# İndeks 1'den 5'e kadar 2'şer atlayarak alalım
print("arr[1:5:2] =", arr[1:5:2]) # Çıktı: [2 4] [cite: 18]

# Tüm diziyi 2'şer atlayarak alalım
print("arr[::2] =", arr[::2]) # Çıktı: [1 3 5 7] [cite: 18]
```

### 2-Boyutlu Dizilerde Dilimleme

2-Boyutlu dizilerde de dilimleme yapabiliriz, hem satırlar hem de sütunlar için:

```python
import numpy as np

arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("\n2D Dizi:\n", arr_2d)

# 2. satırdan (indeks 1), indeks 1'den 4'e kadar (4 hariç) elemanları alalım
print("arr_2d[1, 1:4] =", arr_2d[1, 1:4]) # Çıktı: [7 8 9] [cite: 18]

# Her iki satırdan da sadece 3. sütundaki (indeks 2) elemanları alalım
print("arr_2d[0:2, 2] =", arr_2d[0:2, 2]) # Çıktı: [3 8] [cite: 18]

# Her iki satırdan da indeks 1'den 4'e kadar olan elemanları alalım
print("arr_2d[0:2, 1:4] =\n", arr_2d[0:2, 1:4]) # Çıktı: [[2 3 4] [7 8 9]] [cite: 18]
```

In [3]:
# Slicing İşlemleri
arr = np.array([1,2,3,4,5])

print("arr[1:5] =", arr[1:5])
print("arr[-3::-1] =", arr[-3::-1])
print("arr[1:] =", arr[1:])
print("arr[1:5:2] =", arr[1:5:2])
print("arr[::2] =", arr[::2])

# 2 Boyutlu Dizilerde dilimleme
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("\n2D Dizi:\n",arr_2d)
print("arr_2d[1, 1:4]:", arr_2d[1, 1:4])
print("arr_2d[0:2,2] =", arr_2d[0:2,2])
print("arr_2d[0:2, 1:3]", arr_2d[0:2, 1:3])
print("arr_2d[0:, 2:4]", arr_2d[0:, 2:4])

arr[1:5] = [2 3 4 5]
arr[-3::-1] = [3 2 1]
arr[1:] = [2 3 4 5]
arr[1:5:2] = [2 4]
arr[::2] = [1 3 5]

2D Dizi:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr_2d[1, 1:4]: [7 8 9]
arr_2d[0:2,2] = [3 8]
arr_2d[0:2, 1:3] [[2 3]
 [7 8]]
arr_2d[0:, 2:4] [[3 4]
 [8 9]]


Harika, o zaman dizilerimizin yapı taşlarına, yani içerdikleri verilerin türlerine bakalım! 🧱

---

## 2. Dizi Erişimi ve Temel İşlemler: Veri Tipleri (`dtype`)

NumPy, Python'un standart veri tiplerinin yanı sıra, bilimsel hesaplamalar için optimize edilmiş kendi veri tiplerine sahiptir[cite: 19]. Bunlardan bazıları şunlardır:

* `i` - Tam sayı (integer) [cite: 19]
* `b` - Mantıksal (boolean) [cite: 19]
* `f` - Kayan noktalı sayı (float) [cite: 19]
* `S` - Karakter dizisi (string) [cite: 19]
* `U` - Unicode karakter dizisi (unicode string) [cite: 19]
* `O` - Nesne (object) [cite: 19]

### Veri Tipini Kontrol Etme: `dtype` Özniteliği

Bir NumPy dizisinin hangi veri tipini tuttuğunu öğrenmek için `dtype` özniteliğini kullanırız[cite: 20].

```python
import numpy as np

# Tam sayılardan oluşan dizi
arr_int = np.array([1, 2, 3, 4])
print("Tam Sayı Dizi Tipi:", arr_int.dtype) # Çıktı: int32 (veya int64 olabilir) [cite: 20]

# String'lerden oluşan dizi
arr_str = np.array(['konya', 'ankara', 'bursa'])
print("String Dizi Tipi:", arr_str.dtype) # Çıktı: <U6 (6 karakterlik Unicode) [cite: 20]
```

### Veri Tipini Belirleme

Dizi oluştururken `dtype` parametresini kullanarak veri tipini baştan belirleyebiliriz[cite: 21].

```python
import numpy as np

# Sayıları string olarak saklayalım
arr_s = np.array([1, 2, 3, 4], dtype='S')
print("\nString Olarak Saklanan Dizi:", arr_s) # Çıktı: [b'1' b'2' b'3' b'4'] [cite: 22]
print("Yeni Tipi:", arr_s.dtype) # Çıktı: |S1 [cite: 22]
```

### Veri Tipini Dönüştürme: `astype()` Metodu

Bazen bir dizinin veri tipini değiştirmek isteyebiliriz. Bunun için `astype()` metodunu kullanırız[cite: 23]. Bu metot, eski diziyi değiştirmez, **yeni bir dizi** oluşturur.

```python
import numpy as np

# Float diziyi integer'a çevirelim
arr_float = np.array([1.1, 2.1, 3.1])
print("\nFloat Dizi:", arr_float) # Çıktı: [1.1 2.1 3.1] [cite: 24]
print("Float Tipi:", arr_float.dtype) # Çıktı: float64 [cite: 24]

new_arr_int = arr_float.astype('i') # veya arr_float.astype(int)
print("Integer Dizi:", new_arr_int) # Çıktı: [1 2 3] [cite: 25]
print("Integer Tipi:", new_arr_int.dtype) # Çıktı: int32 [cite: 25]

# Integer diziyi boolean'a çevirelim
arr_int_bool = np.array([1, 0, 3, -5, 0])
print("\nInteger Dizi:", arr_int_bool)

new_arr_bool = arr_int_bool.astype(bool)
print("Boolean Dizi:", new_arr_bool) # Çıktı: [ True False True True False] (0 False, diğer her şey True)
print("Boolean Tipi:", new_arr_bool.dtype) # Çıktı: bool
```

Veri tipleri, bellekte ne kadar yer kaplayacağımızı ve hesaplamaların ne kadar hassas olacağını belirlediği için önemlidir.

In [4]:
import numpy as np

arr_s = np.array([1,2,3,4,5], dtype="S")
print("\nString olarak saklanan dizi:", arr_s)
print("Yeni Tipi:", arr_s.dtype)


String olarak saklanan dizi: [b'1' b'2' b'3' b'4' b'5']
Yeni Tipi: |S1


In [5]:
# astype() => Eski dizinin içindeki verileri dönüştürerek yeni bir dizi oluşturur.

arr_float = np.array([1.1,2.4,3.2,4.5,5.8], dtype="f")
print("Float olarak saklanan dizi:", arr_float)
print("Tipi:", arr_float.dtype)

new_int_arr = arr_float.astype("i") #Eski diziyi bozmaz
print("Float Dizi:", arr_float)
print("Integer Dizi:", new_int_arr)
print("Tipi:", new_int_arr.dtype)

Float olarak saklanan dizi: [1.1 2.4 3.2 4.5 5.8]
Tipi: float32
Float Dizi: [1.1 2.4 3.2 4.5 5.8]
Integer Dizi: [1 2 3 4 5]
Tipi: int32


Tamamdır, şimdi NumPy'daki en önemli ama bazen kafa karıştırıcı konulardan birine geldik: **Kopya (`copy`)** ve **Görünüm (`view`)** arasındaki fark. Bu farkı anlamak, verilerinizin istemeden değişmesini engellemek için çok önemlidir! 🛡️

---

## 2. Dizi Erişimi ve Temel İşlemler: `copy()` vs. `view()`

Bir NumPy dizisiyle çalışırken, bazen onun aynısından bir tane daha oluşturmak isteriz. Ama bu "ayısından bir tane daha"nın orijinaliyle ilişkisi nasıl olacak? İşte burada `copy()` ve `view()` devreye giriyor.

### `copy()` - Bağımsız Klonlama

* `copy()` metodu, orijinal dizinin **tamamen bağımsız, yeni bir kopyasını** oluşturur[cite: 27].
* Bu yeni dizi, bellekte kendi verisine sahiptir.
* Bu yüzden, **orijinal dizide veya kopyasında yapılan değişiklikler birbirini kesinlikle etkilemez**[cite: 27].
* Bir kopyanın `base` özniteliği `None` değerini döndürür, çünkü kendi verisinin sahibidir[cite: 29].

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
kopya = arr.copy()

# Orijinali değiştirelim
arr[0] = 42

print("Orijinal Dizi:", arr)     # Çıktı: [42  2  3  4  5]
print("Kopya Dizi: ", kopya)    # Çıktı: [ 1  2  3  4  5] (Etkilenmedi!) [cite: 31]
print("Kopya Base: ", kopya.base) # Çıktı: None [cite: 31]
```

### `view()` - Bağlantılı Pencere

* `view()` metodu, orijinal dizinin verilerine **bir "pencere" veya "görünüm"** oluşturur[cite: 28].
* Bu görünüm, kendi verisine sahip değildir; orijinal dizinin verilerini kullanır.
* Bu yüzden, **orijinal dizide veya görünümde yapılan değişiklikler birbirini doğrudan etkiler**[cite: 28].
* Bir görünümün `base` özniteliği, baktığı orijinal diziyi döndürür[cite: 29].

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
gorunum = arr.view()

# Orijinali değiştirelim
arr[0] = 42

print("\nOrijinal Dizi:", arr)     # Çıktı: [42  2  3  4  5]
print("Görünüm Dizi: ", gorunum)  # Çıktı: [42  2  3  4  5] (Etkilendi!) [cite: 31]

# Görünümü değiştirelim
gorunum[1] = 99

print("\nOrijinal Dizi:", arr)     # Çıktı: [42 99  3  4  5] (Etkilendi!)
print("Görünüm Dizi: ", gorunum)  # Çıktı: [42 99  3  4  5]
print("Görünüm Base: ", gorunum.base) # Çıktı: [42 99  3  4  5] [cite: 31]
```

**Analoji Zamanı:** `copy()` yapmak, bir belgenin **fotokopisini** çekmek gibidir. Artık elinizde iki ayrı, bağımsız belge vardır. `view()` ise, aynı belgeye bir **büyüteçle** bakmak gibidir; belge hala tektir, sadece ona farklı bir açıdan bakıyorsunuzdur ve belgeye yapacağınız her değişiklik hem normal gözle hem de büyüteçle görülecektir. 📄🔍


---

## 3. Dizi Manipülasyonu ve Fonksiyonlar: Yineleme (Iteration)

Dizilerdeki elemanlar üzerinde tek tek işlem yapmak istediğimizde, Python'un `for` döngülerini kullanabiliriz. Ancak NumPy, bu işi daha verimli ve kolay hale getiren kendi araçlarını da sunar.

### Temel `for` Döngüsü ile Yineleme

Tıpkı listelerde olduğu gibi, NumPy dizileri üzerinde de `for` döngüsü kullanabiliriz. Ancak çok boyutlu dizilerde, her bir elemana ulaşmak için iç içe döngüler yazmamız gerekebilir[cite: 32].

```python
import numpy as np

arr_1d = np.array([1, 2, 3])
print("1B Dizi Yineleme:")
for x in arr_1d:
    print(x)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2B Dizi Yineleme:")
for x in arr_2d:
    for y in x:
        print(y)
```

Gördüğün gibi, boyut sayısı arttıkça iç içe `for` döngüsü sayısı da artar, bu da kodu karmaşıklaştırabilir[cite: 32].

### `nditer()` ile Verimli Yineleme

İşte burada NumPy'ın `nditer()` fonksiyonu devreye giriyor! Bu fonksiyon, dizinin boyutu ne olursa olsun, tüm elemanları üzerinde **tek bir döngüyle** gezinmemizi sağlayan bir yardımcıdır[cite: 35].

```python
import numpy as np

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3B Dizi nditer() ile Yineleme:")
for x in np.nditer(arr_3d):
    print(x) # Çıktı: 1 2 3 4 5 6 7 8
```

Çok daha basit, değil mi? `nditer()`, özellikle yüksek boyutlu dizilerde hayat kurtarıcı olabilir.

### `ndenumerate()` ile İndeksli Yineleme

Bazen elemanın kendisiyle birlikte **indeksine** de ihtiyacımız olur. `ndenumerate()` fonksiyonu tam da bunu yapar: Bize her elemanın hem **indeksini (bir demet olarak)** hem de **değerini** verir[cite: 37].

```python
import numpy as np

arr = np.array([[1, 2], [3, 4]])
print("\n2B Dizi ndenumerate() ile Yineleme:")
for idx, x in np.ndenumerate(arr):
    print(idx, x)

# Çıktı:
# (0, 0) 1
# (0, 1) 2
# (1, 0) 3
# (1, 1) 4
```

Bu, belirli bir konumdaki elemanlarla işlem yaparken çok kullanışlıdır.

**Analoji Zamanı:** `for` döngüsüyle dolaşmak, bir apartmandaki her daireye kat kat, kapı kapı gitmek gibidir. `nditer()` ise sizi sıradaki daireye ışınlayan sihirli bir anahtar gibidir. `ndenumerate()` ise bu sihirli anahtarın size daire numarasını da söyleyen versiyonudur! 🔑🚪

---

In [6]:
import numpy as np

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Dizi üzerinde nditer() ile Yineleme:")
for x in np.nditer(arr_3d):
    print(x)

print("3D dizi üzerinde ndenumerate() ile Yineleme:")
for x in np.ndenumerate(arr_3d):
    print(x)

3D Dizi üzerinde nditer() ile Yineleme:
1
2
3
4
5
6
7
8
3D dizi üzerinde ndenumerate() ile Yineleme:
((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 1, 0), 3)
((0, 1, 1), 4)
((1, 0, 0), 5)
((1, 0, 1), 6)
((1, 1, 0), 7)
((1, 1, 1), 8)


Harika, hız kesmeden devam edelim! Şimdi de elimizdeki dizileri nasıl bir araya getireceğimize veya tam tersi, nasıl parçalara ayıracağımıza bakacağız. Bu işlemler, verileri düzenlerken çok işimize yarayacak. 🏗️

---

## 3. Dizi Manipülasyonu ve Fonksiyonlar: Birleştirme ve Bölme

### Dizileri Birleştirme

NumPy'da dizileri birleştirmenin temel iki yolu vardır: `concatenate()` ve `stack()`.

#### `concatenate()` - Uç Uca Ekleme

Bu fonksiyon, iki veya daha fazla diziyi **mevcut eksenleri boyunca** birleştirir.

```python
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
birlesik_1d = np.concatenate((arr1, arr2))
print("1D Birleştirme:\n", birlesik_1d) # Çıktı: [1 2 3 4 5 6] [cite: 41]

arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Satır bazlı birleştirme (axis=0, varsayılan)
birlesik_satir = np.concatenate((arr3, arr4), axis=0)
print("\nSatır Bazlı Birleştirme (axis=0):\n", birlesik_satir) # Çıktı: [[1 2] [3 4] [5 6] [7 8]] [cite: 41]

# Sütun bazlı birleştirme (axis=1)
birlesik_sutun = np.concatenate((arr3, arr4), axis=1)
print("\nSütun Bazlı Birleştirme (axis=1):\n", birlesik_sutun) # Çıktı: [[1 2 5 6] [3 4 7 8]] [cite: 41]
```

#### `stack()` - Üst Üste Yığma

`stack()` da birleştirme yapar, ancak bunu **yeni bir eksen ekleyerek** yapar[cite: 42]. Yani dizileri "üst üste yığar".

```python
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Yeni eksen 0 olacak şekilde yığma
yigin_0 = np.stack((arr1, arr2), axis=0)
print("\nStack (axis=0):\n", yigin_0) # Çıktı: [[1 2 3] [4 5 6]] [cite: 42]

# Yeni eksen 1 olacak şekilde yığma
yigin_1 = np.stack((arr1, arr2), axis=1)
print("\nStack (axis=1):\n", yigin_1) # Çıktı: [[1 4] [2 5] [3 6]] [cite: 42]
```

### Dizileri Bölme

#### `array_split()` - Parçalara Ayırma

Bu fonksiyon, bir diziyi belirttiğiniz sayıda parçaya böler[cite: 42]. Bölme işlemi tam olarak eşit olmasa bile çalışır[cite: 44].

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# 3 parçaya bölelim
bolunmus_3 = np.array_split(arr, 3)
print("\n3 Parçaya Bölme:\n", bolunmus_3) # Çıktı: [array([1, 2]), array([3, 4]), array([5, 6])] [cite: 43]
print("İlk Parça:", bolunmus_3[0]) # Çıktı: [1 2] [cite: 43]

# 4 parçaya bölelim (eşit olmayacak)
bolunmus_4 = np.array_split(arr, 4)
print("\n4 Parçaya Bölme:\n", bolunmus_4) # Çıktı: [array([1, 2]), array([3, 4]), array([5]), array([6])] [cite: 44]

# 2D diziyi sütun bazlı (axis=1) 3 parçaya bölelim
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bolunmus_2d_sutun = np.array_split(arr_2d, 3, axis=1)
print("\n2D Sütun Bazlı Bölme:\n", bolunmus_2d_sutun)
```

---

In [7]:
import numpy as np

# concatenate => Uç Uca ekleme
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combine = np.concatenate((arr1, arr2))
print("1D Birleştirme:",combine)

print("-------------------------------------")
print("2D birleştirme")
arr_3 = np.array([[1,2], [3,4]])
arr_4 = np.array([[5,6], [7,8]])
combine_row = np.concatenate((arr_3, arr_4), axis=0) # Matrisleri satır satır birleştirir tüm satırları alır ve sütunlara aktarır.
print("\nSatır bazlı birleştirme (axis=0):\n", combine_row)

combine_col = np.concatenate((arr_3, arr_4), axis=1) # Kolonları tek bir satır haline getirdi!
print("\nSutün bazlı birleştirme (axis=1):\n", combine_col)

print("--------------------------------------")
print("Stack")
# stack() => Üst üste Yığma
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

stack_0 = np.stack((arr_1, arr_2), axis=0) # Satırları yığıyor
print("\nStack (axis=0):\n", stack_0)

stack_1 = np.stack((arr_1, arr_2), axis=1) # Sütunları yığıyor
print("\nStack (axis=1):\n", stack_1)

1D Birleştirme: [1 2 3 4 5 6]
-------------------------------------
2D birleştirme

Satır bazlı birleştirme (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Sutün bazlı birleştirme (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]
--------------------------------------
Stack

Stack (axis=0):
 [[1 2 3]
 [4 5 6]]

Stack (axis=1):
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# 3 parçaya bölelim
bolunmus_3 = np.array_split(arr, 3)
print("\n3 Parçaya Bölme:\n", bolunmus_3) # Çıktı: [array([1, 2]), array([3, 4]), array([5, 6])] [cite: 43]
print("İlk Parça:", bolunmus_3[0]) # Çıktı: [1 2] [cite: 43]

# 4 parçaya bölelim (eşit olmayacak)
bolunmus_4 = np.array_split(arr, 4)
print("\n4 Parçaya Bölme:\n", bolunmus_4) # Çıktı: [array([1, 2]), array([3, 4]), array([5]), array([6])] [cite: 44]

# 2D diziyi sütun bazlı (axis=1) 3 parçaya bölelim
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bolunmus_2d_sutun = np.array_split(arr_2d, 3, axis=1)
print("\n2D Sütun Bazlı Bölme:\n", bolunmus_2d_sutun)


3 Parçaya Bölme:
 [array([1, 2]), array([3, 4]), array([5, 6])]
İlk Parça: [1 2]

4 Parçaya Bölme:
 [array([1, 2]), array([3, 4]), array([5]), array([6])]

2D Sütun Bazlı Bölme:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [9]:
# Senaryo

notlar_9a = np.array([[80, 75], [65, 70], [90, 88]])
notlar_9b = np.array([[72, 68], [85, 90]])
turkce_9a = np.array([70, 80, 95])

# Tüm 9. sınıf öğrencilerin matematik ve fizik notlarını tek bir dizide toplayalım
notlar_9 = np.concatenate((notlar_9a, notlar_9b), axis=0)
print("9. sınıf mat ve fizik notları: ", notlar_9)

# Türkçe notlarını da mat ve fizik ile birlikte tutma
turkce_sutun =  turkce_9a.reshape(-1, 1)
print("Türkçe sütun:", turkce_sutun)
notlar_9a = np.concatenate((notlar_9a, turkce_sutun), axis=1)
print(f"\n Notlar 9a: {notlar_9a}")

9. sınıf mat ve fizik notları:  [[80 75]
 [65 70]
 [90 88]
 [72 68]
 [85 90]]
Türkçe sütun: [[70]
 [80]
 [95]]

 Notlar 9a: [[80 75 70]
 [65 70 80]
 [90 88 95]]


Harika! Şimdi NumPy'ın veri analizindeki gücünü gerçekten gösterecek olan **arama, sıralama ve filtreleme** konularına dalalım. Unutma, amacımız `[75, 42, 91, 55, 30, 88, 65, 42, 99]` gibi bir not listesini anlamlı hale getirmek! 🧐

---

## 3. Dizi Manipülasyonu ve Fonksiyonlar: Arama, Sıralama, Filtreleme

### Dizilerde Arama: `where()`

`where()` fonksiyonu, bir dizi içinde **belirli bir koşulu sağlayan elemanların indekslerini (konumlarını)** bulmamızı sağlar[cite: 46].

* **Neden Önemli?** Belirli bir değere sahip verileri (örneğin, 42 alan öğrenciler) veya belirli bir özelliği taşıyan verileri (örneğin, çift sayılar) anında tespit etmek için.

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

# 4'e eşit olan elemanların indekslerini bulalım
x = np.where(arr == 4) # [cite: 47]
print("4'e eşit olanların indeksleri:", x) # Çıktı: (array([3, 5, 6], dtype=int64),) [cite: 47]

# Çift sayıların indekslerini bulalım
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.where(arr2 % 2 == 0) # [cite: 47]
print("Çift sayıların indeksleri:", y) # Çıktı: (array([1, 3, 5, 7], dtype=int64),) [cite: 47]

# Senaryomuza Uygulama: 42 alan öğrencilerin indeksleri
notlar = np.array([75, 42, 91, 55, 30, 88, 65, 42, 99])
kim_42_aldi = np.where(notlar == 42)
print("42 alanların indeksleri:", kim_42_aldi) # Çıktı: (array([1, 7], dtype=int64),)
```
Gördüğün gibi, `where` bize doğrudan 1. ve 7. indeksteki öğrencilerin 42 aldığını söylüyor!

### Dizilerde Sıralama: `sort()`

`sort()` fonksiyonu, bir dizinin elemanlarını **küçükten büyüğe** (veya alfabetik olarak) sıralar[cite: 48].

* **Neden Önemli?** Verinin dağılımını görmek, en küçük/en büyük değerleri bulmak, veriyi düzenli bir şekilde sunmak için.

```python
import numpy as np

arr_sayi = np.array([3, 2, 0, 1])
print("\nSayısal Sıralama:", np.sort(arr_sayi)) # Çıktı: [0 1 2 3] [cite: 49]

arr_str = np.array(['konya', 'ankara', 'bursa'])
print("String Sıralama:", np.sort(arr_str)) # Çıktı: ['ankara' 'bursa' 'konya'] [cite: 49]

arr_2d = np.array([[3, 2, 4], [5, 0, 1]])
print("2D Sıralama:\n", np.sort(arr_2d)) # Çıktı: [[2 3 4] [0 1 5]] (Her satırı kendi içinde sıralar) [cite: 49]

# Senaryomuza Uygulama: Notları sıralayalım
notlar = np.array([75, 42, 91, 55, 30, 88, 65, 42, 99])
sirali_notlar = np.sort(notlar)
print("Sıralı Notlar:", sirali_notlar) # Çıktı: [30 42 42 55 65 75 88 91 99]
```
Artık en düşük notun 30, en yükseğin 99 olduğunu ve notların nasıl dağıldığını kolayca görebiliyoruz.

### Dizileri Filtreleme

Filtreleme, mevcut bir diziden **belirli bir koşulu sağlayan elemanları seçerek** yeni bir dizi oluşturmaktır[cite: 50]. Bunun için **Boolean indeksleme** denen güçlü bir yöntem kullanılır.

* **Neden Önemli?** Veri setimizden sadece ilgilendiğimiz, belirli kriterlere uyan alt kümeleri (örneğin, 50'den yüksek notlar) çekip almak için.

```python
import numpy as np

arr = np.array([41, 42, 43, 44])

# 1. Yöntem: Manuel Boolean Dizi ile
x = [True, False, True, False] # [cite: 52]
newarr1 = arr[x] # [cite: 52]
print("\nManuel Filtreleme:", newarr1) # Çıktı: [41 43] [cite: 52]

# 2. Yöntem: Koşuldan Filtre Oluşturma
filter_arr = arr > 42 # [cite: 53]
newarr2 = arr[filter_arr] # [cite: 54]
print("Koşullu Filtreleme:", newarr2) # Çıktı: [43 44] [cite: 54]

# 3. Yöntem: Doğrudan Filtreleme (En yaygını)
newarr3 = arr[arr > 42] # [cite: 54]
print("Doğrudan Filtreleme:", newarr3) # Çıktı: [43 44] [cite: 54]

# Senaryomuza Uygulama: Geçen öğrencilerin notları (50 ve üzeri)
notlar = np.array([75, 42, 91, 55, 30, 88, 65, 42, 99])
gecen_notlar = notlar[notlar >= 50]
print("Geçenlerin Notları:", gecen_notlar) # Çıktı: [75 91 55 88 65 99]
```
Anında sadece geçen öğrencilerin notlarını içeren yeni bir dizi oluşturduk!

---

In [ ]:
import numpy as np
# Where

arr = np.array([1, 2, 3, 4, 5, 3, 3])
# 3 e eşit olanların indekslerini getir.
x = np.where(arr == 3)
print("3 e eşit değerli sayıların indeksi,", x)

arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.where(arr2 % 2 == 0)
print("Çift sayıların index değerleri", y)

new_arr = np.where(arr % 2 == 0, 1, 0) # Eğer girilen koşul doğru ise 1 yanlış ise 0 değerini döndürür.
print(new_arr)